import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Download, MoreHorizontal, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { entities } from '../../config/entities'
import { useAuth } from '../../context/AuthContext'
import { demoData } from '../../data/demo'
import { createRow, deleteRow, listRows, updateRow } from '../../services/crud'
import type { Field, RecordRow } from '../../types'
import { Badge, Button, EmptyState, Modal, Spinner } from '../ui'
import { PageHeader } from '../PageHeader'

const label=(value:unknown)=>String(value??'—').replaceAll('_',' ')
const money=(value:unknown)=>typeof value==='number'||(/^[-]?\d+(\.\d+)?$/.test(String(value))&&String(value)!=='')?new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(value)):label(value)
const tone=(value:unknown)=>['active','paid','confirmed','completed','available','resolved','delivered','sent'].includes(String(value))?'success':['pending','processing','in_progress','draft','prospect'].includes(String(value))?'warning':['failed','rejected','cancelled','suspended','out_of_stock'].includes(String(value))?'danger':'neutral'

export function EntityPage({entityKey,readOnly=false}:{entityKey:string;readOnly?:boolean}){
 const config=entities[entityKey]; const {demoRole}=useAuth(); const [rows,setRows]=useState<RecordRow[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const [editing,setEditing]=useState<RecordRow|null|undefined>(undefined);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function load(){setLoading(true);setError('');try{setRows(demoRole?[...(demoData[config.table]??[])]:await listRows(config.table))}catch(e){setError(e instanceof Error?e.message:'Unable to load records')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[config.table,demoRole])
 const filtered=useMemo(()=>rows.filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))),[rows,query])
 async function save(values:RecordRow){setBusy(true);setError('');try{if(demoRole){if(editing?.id)setRows(x=>x.map(row=>row.id===editing.id?{...row,...values}:row));else setRows(x=>[{id:crypto.randomUUID(),created_at:new Date().toISOString(),...values},...x])}else{editing?.id?await updateRow(config.table,String(editing.id),values):await createRow(config.table,values);await load()}setEditing(undefined)}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 async function remove(row:RecordRow){if(!confirm(`Delete this ${config.singular.toLowerCase()}?`))return;try{if(demoRole)setRows(x=>x.filter(r=>r.id!==row.id));else{await deleteRow(config.table,String(row.id));await load()}}catch(e){setError(e instanceof Error?e.message:'Unable to delete')}}
 return <><PageHeader title={config.title} description={config.description} action={!readOnly?<Button onClick={()=>setEditing(null)}><Plus size={18}/> Add {config.singular}</Button>:undefined}/>
  <section className="stat-strip"><div><span>Total records</span><strong>{rows.length}</strong></div><div><span>Active / complete</span><strong>{rows.filter(r=>tone(r.status??r.payment_status)==='success').length}</strong></div><div><span>Needs attention</span><strong>{rows.filter(r=>tone(r.status??r.payment_status)==='warning').length}</strong></div></section>
  <section className="data-panel"><div className="table-tools"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}...`}/></label><button className="secondary-button"><Download size={17}/> Export</button></div>
   {error&&<div className="alert">{error}</div>}{loading?<Spinner/>:filtered.length===0?<EmptyState title={`No ${config.title.toLowerCase()} found`} body="Create your first record or change the current search." action={!readOnly?<Button onClick={()=>setEditing(null)}><Plus size={18}/> Add {config.singular}</Button>:undefined}/>:<div className="table-wrap"><table><thead><tr>{config.columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}{!readOnly&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(row=><tr key={String(row.id)}>{config.columns.map(c=><td key={c}>{c.includes('amount')||c==='price'||c==='total_spent'||c==='balance_after'?money(row[c]):c.includes('status')?<Badge tone={tone(row[c])}>{label(row[c])}</Badge>:label(row[c])}</td>)}{!readOnly&&<td><div className="row-actions"><button onClick={()=>setEditing(row)} aria-label="Edit"><Pencil size={16}/></button><button onClick={()=>void remove(row)} aria-label="Delete" className="danger"><Trash2 size={16}/></button><button aria-label="More"><MoreHorizontal size={16}/></button></div></td>}</tr>)}</tbody></table></div>}
  </section>{editing!==undefined&&<EntityForm fields={config.fields} initial={editing} title={`${editing?'Edit':'Add'} ${config.singular}`} busy={busy} onClose={()=>setEditing(undefined)} onSave={save}/>}</>
}

function EntityForm({fields,initial,title,busy,onClose,onSave}:{fields:Field[];initial:RecordRow|null;title:string;busy:boolean;onClose:()=>void;onSave:(v:RecordRow)=>Promise<void>}){
 const [values,setValues]=useState<RecordRow>(()=>Object.fromEntries(fields.map(f=>[f.key,initial?.[f.key]??(f.type==='boolean'?false:'')])));function change(key:string,value:string|boolean){setValues(v=>({...v,[key]:value}))}
 function submit(e:FormEvent){e.preventDefault();const normalized=Object.fromEntries(Object.entries(values).map(([k,v])=>{const f=fields.find(x=>x.key===k);return [k,f?.type==='number'||f?.type==='currency'?Number(v):v]}));void onSave(normalized)}
 return <Modal title={title} onClose={onClose} wide><form onSubmit={submit} className="entity-form"><div className="form-grid">{fields.map(f=><label key={f.key} className={f.type==='textarea'?'full':''}><span>{f.label}{f.required&&' *'}</span>{f.type==='textarea'?<textarea rows={4} required={f.required} value={String(values[f.key]??'')} onChange={e=>change(f.key,e.target.value)}/>:f.type==='select'?<select required={f.required} value={String(values[f.key]??'')} onChange={e=>change(f.key,e.target.value)}><option value="">Select {f.label.toLowerCase()}</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='boolean'?<input type="checkbox" checked={Boolean(values[f.key])} onChange={e=>change(f.key,e.target.checked)}/>:<input required={f.required} type={f.type==='currency'?'number':f.type} min={f.type==='currency'||f.type==='number'?0:undefined} value={String(values[f.key]??'')} onChange={e=>change(f.key,e.target.value)} placeholder={f.placeholder}/>}</label>)}</div><footer><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><Button disabled={busy}>{busy?'Saving...':'Save record'}</Button></footer></form></Modal>
}
