import { useState, type FormEvent } from 'react'
import { useNavigate } from '@tanstack/react-router'
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import type { Role } from '../types'
import { Button } from '../components/ui'

const roles:Role[]=['super_admin','staff','marketer','partner','customer']
export function LoginPage(){const {signIn,enterDemo}=useAuth();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);await navigate({to:'/'})}catch(e){setError(e instanceof Error?e.message:'Sign in failed')}finally{setBusy(false)}}
 async function demo(role:Role){enterDemo(role);await navigate({to:`/${role}/overview`})}
 return <main className="login-page"><section className="login-panel"><div className="login-brand"><div className="brand-mark">RH</div><span>Rooftop Hub</span></div><div className="login-copy"><p className="eyebrow">Sales command centre</p><h1>Good to see you again.</h1><p>Manage customers, orders, performance and earnings from one secure workspace.</p></div><form onSubmit={submit}><label><span>Email address</span><div className="input-icon"><Mail size={18}/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@rooftophub.ng"/></div></label><label><span>Password</span><div className="input-icon"><LockKeyhole size={18}/><input type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(x=>!x)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="alert">{error}</div>}<Button disabled={busy} className="full-button">{busy?'Signing in...':'Sign in'} <ArrowRight size={18}/></Button></form><div className="demo-access"><span>Client preview access</span><div>{roles.map(r=><button key={r} onClick={()=>void demo(r)}>{r.replace('_',' ')}</button>)}</div></div></section><section className="login-visual"><div className="roof-lines"/><div className="visual-content"><div className="trust-pill"><ShieldCheck size={18}/> Secure sales operations</div><h2>Every customer. Every sale. One clear view.</h2><p>Turn daily activities into measurable performance, transparent commissions and stronger customer relationships.</p><div className="visual-stats"><div><strong>₦24.8M</strong><span>Monthly sales</span></div><div><strong>68%</strong><span>Returning customers</span></div><div><strong>92%</strong><span>Target progress</span></div></div></div></section></main>}
