create extension if not exists pgcrypto;

create type public.app_role as enum ('super_admin','staff','marketer','partner','customer');
create type public.account_status as enum ('active','suspended','pending');

create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text not null, email text not null unique, phone text, avatar_url text,
 role public.app_role not null default 'customer', status public.account_status not null default 'pending',
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.customers (
 id uuid primary key default gen_random_uuid(), customer_code text not null unique, profile_id uuid references public.profiles(id) on delete set null,
 full_name text not null, email text, phone text not null, address text, customer_status text not null default 'prospect', total_spent numeric(14,2) not null default 0,
 assigned_staff_id uuid references public.profiles(id) on delete set null, marketer_id uuid references public.profiles(id) on delete set null, partner_id uuid references public.profiles(id) on delete set null,
 created_by uuid references public.profiles(id) on delete set null default auth.uid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.product_categories (id uuid primary key default gen_random_uuid(),name text not null unique,description text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.products (
 id uuid primary key default gen_random_uuid(),category_id uuid references public.product_categories(id) on delete set null,sku text not null unique,name text not null,description text,
 price numeric(14,2) not null check(price>=0),stock_quantity integer not null default 0 check(stock_quantity>=0),bulk_min_quantity integer,bulk_discount_percent numeric(5,2) default 0,image_url text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.orders (
 id uuid primary key default gen_random_uuid(),order_number text not null unique,customer_id uuid references public.customers(id) on delete restrict,subtotal numeric(14,2) not null default 0,discount_amount numeric(14,2) not null default 0,total_amount numeric(14,2) not null default 0,
 payment_status text not null default 'pending',fulfilment_status text not null default 'new',notes text,created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.order_items (id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,quantity integer not null check(quantity>0),unit_price numeric(14,2) not null,discount_amount numeric(14,2) not null default 0,line_total numeric(14,2) not null,created_at timestamptz not null default now());
create table public.sales (
 id uuid primary key default gen_random_uuid(),reference text not null unique,order_id uuid references public.orders(id) on delete set null,customer_id uuid references public.customers(id) on delete restrict,responsible_staff_id uuid references public.profiles(id) on delete set null,marketer_id uuid references public.profiles(id) on delete set null,partner_id uuid references public.profiles(id) on delete set null,
 sale_date date not null default current_date,subtotal numeric(14,2) not null default 0,discount_amount numeric(14,2) not null default 0,total_amount numeric(14,2) not null default 0,payment_method text not null,payment_status text not null default 'pending',status text not null default 'draft',created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.sale_items (id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id) on delete cascade,product_id uuid not null references public.products(id) on delete restrict,quantity integer not null check(quantity>0),unit_price numeric(14,2) not null,discount_amount numeric(14,2) not null default 0,line_total numeric(14,2) not null,created_at timestamptz not null default now());
create table public.sales_targets (id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,period_start date not null,period_end date not null,target_amount numeric(14,2) not null check(target_amount>=0),achieved_amount numeric(14,2) not null default 0,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(profile_id,period_start,period_end));
create table public.commissions (id uuid primary key default gen_random_uuid(),beneficiary_id uuid not null references public.profiles(id) on delete cascade,sale_id uuid references public.sales(id) on delete restrict,commission_type text not null,rate numeric(6,3) not null default 0,amount numeric(14,2) not null check(amount>=0),status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.wallets (id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.profiles(id) on delete cascade,balance numeric(14,2) not null default 0,available_balance numeric(14,2) not null default 0,updated_at timestamptz not null default now());
create table public.wallet_transactions (id uuid primary key default gen_random_uuid(),wallet_id uuid references public.wallets(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,transaction_type text not null,amount numeric(14,2) not null,balance_after numeric(14,2),description text not null,reference text,created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now());
create table public.withdrawals (id uuid primary key default gen_random_uuid(),reference text not null unique,profile_id uuid not null references public.profiles(id) on delete cascade,amount numeric(14,2) not null check(amount>0),bank_name text not null,account_number text not null,account_name text not null,status text not null default 'pending',rejection_reason text,requested_at timestamptz not null default now(),processed_at timestamptz,processed_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(),reference text not null unique,order_id uuid references public.orders(id) on delete set null,sale_id uuid references public.sales(id) on delete set null,customer_id uuid references public.customers(id) on delete set null,provider text,provider_reference text,amount numeric(14,2) not null check(amount>0),method text not null,status text not null default 'pending',paid_at timestamptz,recorded_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(),title text not null,message text not null,channel text not null,audience text not null,status text not null default 'draft',scheduled_at timestamptz,sent_at timestamptz,created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customer_feedback (id uuid primary key default gen_random_uuid(),customer_id uuid references public.customers(id) on delete set null,subject text not null,message text not null,feedback_type text not null default 'feedback',priority text not null default 'normal',status text not null default 'open',assigned_profile_id uuid references public.profiles(id) on delete set null,created_by uuid references public.profiles(id) on delete set null default auth.uid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.app_settings (id uuid primary key default gen_random_uuid(),setting_group text not null,setting_key text not null,setting_value jsonb not null default '{}'::jsonb,is_public boolean not null default false,updated_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(setting_group,setting_key));
create table public.audit_logs (id bigint generated always as identity primary key,actor_id uuid references public.profiles(id) on delete set null,action text not null,table_name text not null,record_id text,old_values jsonb,new_values jsonb,created_at timestamptz not null default now());

create index customers_staff_idx on public.customers(assigned_staff_id);create index customers_marketer_idx on public.customers(marketer_id);create index customers_partner_idx on public.customers(partner_id);create index sales_customer_idx on public.sales(customer_id);create index sales_staff_idx on public.sales(responsible_staff_id);create index commissions_beneficiary_idx on public.commissions(beneficiary_id);create index wallet_transactions_profile_idx on public.wallet_transactions(profile_id);create index orders_customer_idx on public.orders(customer_id);

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create or replace function private.current_app_role() returns public.app_role language sql stable security definer set search_path='' as $$ select role from public.profiles where id=(select auth.uid()) and status='active' limit 1 $$;
create or replace function private.is_super_admin() returns boolean language sql stable security definer set search_path='' as $$ select coalesce((select private.current_app_role()='super_admin'),false) $$;
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,full_name,email,role,status) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.email,coalesce((new.raw_app_meta_data->>'role')::public.app_role,'customer'),'pending');insert into public.wallets(profile_id) values(new.id);return new;end;$$;
revoke all on function private.current_app_role() from public,anon;revoke all on function private.is_super_admin() from public,anon;revoke all on function private.handle_new_user() from public,anon,authenticated;grant execute on function private.current_app_role(),private.is_super_admin() to authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.handle_new_user();
create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now();return new;end;$$;
do $$ declare t text;begin foreach t in array array['profiles','customers','product_categories','products','orders','sales','sales_targets','commissions','withdrawals','payments','notifications','customer_feedback','app_settings'] loop execute format('create trigger touch_%I before update on public.%I for each row execute function public.touch_updated_at()',t,t);end loop;end $$;

do $$ declare t text;begin foreach t in array array['profiles','customers','product_categories','products','orders','order_items','sales','sale_items','sales_targets','commissions','wallets','wallet_transactions','withdrawals','payments','notifications','customer_feedback','app_settings','audit_logs'] loop execute format('alter table public.%I enable row level security',t);execute format('grant select,insert,update,delete on public.%I to authenticated',t);end loop;end $$;
grant usage,select on sequence public.audit_logs_id_seq to authenticated;

create policy profiles_select on public.profiles for select to authenticated using(private.is_super_admin() or id=(select auth.uid()));
create policy profiles_admin_insert on public.profiles for insert to authenticated with check(private.is_super_admin());create policy profiles_update on public.profiles for update to authenticated using(private.is_super_admin() or id=(select auth.uid())) with check(private.is_super_admin() or id=(select auth.uid()));create policy profiles_admin_delete on public.profiles for delete to authenticated using(private.is_super_admin());
create policy customers_select on public.customers for select to authenticated using(private.is_super_admin() or assigned_staff_id=(select auth.uid()) or marketer_id=(select auth.uid()) or partner_id=(select auth.uid()) or profile_id=(select auth.uid()) or created_by=(select auth.uid()));
create policy customers_insert on public.customers for insert to authenticated with check(private.is_super_admin() or private.current_app_role() in ('staff','marketer'));create policy customers_update on public.customers for update to authenticated using(private.is_super_admin() or assigned_staff_id=(select auth.uid()) or marketer_id=(select auth.uid()) or created_by=(select auth.uid())) with check(private.is_super_admin() or assigned_staff_id=(select auth.uid()) or marketer_id=(select auth.uid()) or created_by=(select auth.uid()));create policy customers_admin_delete on public.customers for delete to authenticated using(private.is_super_admin());
create policy catalogue_select_categories on public.product_categories for select to authenticated using(true);create policy catalogue_select_products on public.products for select to authenticated using(true);
create policy categories_admin_all on public.product_categories for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());create policy products_admin_all on public.products for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy orders_select on public.orders for select to authenticated using(private.is_super_admin() or created_by=(select auth.uid()) or customer_id in(select id from public.customers where profile_id=(select auth.uid())));create policy orders_insert on public.orders for insert to authenticated with check(private.is_super_admin() or created_by=(select auth.uid()));create policy orders_update on public.orders for update to authenticated using(private.is_super_admin() or created_by=(select auth.uid())) with check(private.is_super_admin() or created_by=(select auth.uid()));create policy orders_delete on public.orders for delete to authenticated using(private.is_super_admin());
create policy order_items_select on public.order_items for select to authenticated using(order_id in(select id from public.orders));create policy order_items_write on public.order_items for all to authenticated using(private.is_super_admin() or order_id in(select id from public.orders where created_by=(select auth.uid()))) with check(private.is_super_admin() or order_id in(select id from public.orders where created_by=(select auth.uid())));
create policy sales_select on public.sales for select to authenticated using(private.is_super_admin() or responsible_staff_id=(select auth.uid()) or marketer_id=(select auth.uid()) or partner_id=(select auth.uid()) or created_by=(select auth.uid()) or customer_id in(select id from public.customers where profile_id=(select auth.uid())));create policy sales_insert on public.sales for insert to authenticated with check(private.is_super_admin() or private.current_app_role()='staff');create policy sales_update on public.sales for update to authenticated using(private.is_super_admin() or (responsible_staff_id=(select auth.uid()) and status='draft')) with check(private.is_super_admin() or responsible_staff_id=(select auth.uid()));create policy sales_delete on public.sales for delete to authenticated using(private.is_super_admin() or (created_by=(select auth.uid()) and status='draft'));
create policy sale_items_select on public.sale_items for select to authenticated using(sale_id in(select id from public.sales));create policy sale_items_write on public.sale_items for all to authenticated using(private.is_super_admin() or sale_id in(select id from public.sales where created_by=(select auth.uid()) and status='draft')) with check(private.is_super_admin() or sale_id in(select id from public.sales where created_by=(select auth.uid()) and status='draft'));
create policy targets_select on public.sales_targets for select to authenticated using(private.is_super_admin() or profile_id=(select auth.uid()));create policy targets_admin_all on public.sales_targets for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy commissions_select on public.commissions for select to authenticated using(private.is_super_admin() or beneficiary_id=(select auth.uid()));create policy commissions_admin_all on public.commissions for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy wallets_select on public.wallets for select to authenticated using(private.is_super_admin() or profile_id=(select auth.uid()));create policy wallets_admin_all on public.wallets for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy wallet_tx_select on public.wallet_transactions for select to authenticated using(private.is_super_admin() or profile_id=(select auth.uid()));create policy wallet_tx_admin_all on public.wallet_transactions for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy withdrawal_select on public.withdrawals for select to authenticated using(private.is_super_admin() or profile_id=(select auth.uid()));create policy withdrawal_insert on public.withdrawals for insert to authenticated with check(profile_id=(select auth.uid()));create policy withdrawal_update on public.withdrawals for update to authenticated using(private.is_super_admin()) with check(private.is_super_admin());create policy withdrawal_delete on public.withdrawals for delete to authenticated using(private.is_super_admin() or (profile_id=(select auth.uid()) and status='pending'));
create policy payments_select on public.payments for select to authenticated using(private.is_super_admin() or recorded_by=(select auth.uid()) or customer_id in(select id from public.customers where profile_id=(select auth.uid())));create policy payments_admin_all on public.payments for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());create policy payments_staff_insert on public.payments for insert to authenticated with check(private.current_app_role()='staff' and recorded_by=(select auth.uid()));
create policy notifications_select on public.notifications for select to authenticated using(private.is_super_admin() or status='sent' and audience in('all',private.current_app_role()::text));create policy notifications_admin_all on public.notifications for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());
create policy feedback_select on public.customer_feedback for select to authenticated using(private.is_super_admin() or created_by=(select auth.uid()) or assigned_profile_id=(select auth.uid()));create policy feedback_insert on public.customer_feedback for insert to authenticated with check(created_by=(select auth.uid()) or private.is_super_admin());create policy feedback_update on public.customer_feedback for update to authenticated using(private.is_super_admin() or assigned_profile_id=(select auth.uid()) or created_by=(select auth.uid())) with check(private.is_super_admin() or assigned_profile_id=(select auth.uid()) or created_by=(select auth.uid()));create policy feedback_delete on public.customer_feedback for delete to authenticated using(private.is_super_admin() or created_by=(select auth.uid()));
create policy settings_read on public.app_settings for select to authenticated using(private.is_super_admin() or is_public);create policy settings_admin_all on public.app_settings for all to authenticated using(private.is_super_admin()) with check(private.is_super_admin());create policy audit_admin_select on public.audit_logs for select to authenticated using(private.is_super_admin());create policy audit_insert on public.audit_logs for insert to authenticated with check(actor_id=(select auth.uid()));

insert into public.app_settings(setting_group,setting_key,setting_value,is_public) values
('company','profile','{"name":"Rooftop Hub","currency":"NGN","timezone":"Africa/Lagos"}',true),
('commissions','defaults','{"staff_rate":3,"marketer_rate":2,"partner_rate":5,"availability_hours":24}',false),
('withdrawals','policy','{"minimum":10000,"maximum_daily":500000,"frequency":"weekly","auto_approve":false}',false),
('security','policy','{"session_hours":8,"password_min_length":10,"audit_retention_days":365}',false);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-images','product-images',true,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy product_images_read on storage.objects for select to anon,authenticated using(bucket_id='product-images');create policy product_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='product-images' and private.is_super_admin());create policy product_images_admin_update on storage.objects for update to authenticated using(bucket_id='product-images' and private.is_super_admin()) with check(bucket_id='product-images' and private.is_super_admin());create policy product_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='product-images' and private.is_super_admin());
